### ISSUE TITLE
Incorrect template is used for the method

### ISSUE THREAD

**Issue by s-siplivy** [arasplm/ArasVSMethodPlugin#10]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.4.46]
- Innovator 11.0 SP15

### Description
Replace this text with a short description

### Steps to recreate
1. Create c# method with the following code (tp_ItemInfoContentGenerator method from Tech Doc solution):
[example.txt](https://github.com/arasplm/ArasVSMethodPlugin/files/2796760/example.txt)
2. Open the method with plugin

### Current behavior
VS method is generated based on standard template

### Expected behavior
First line with MethodTemplateName should be used to define used template

**Comment by mkubrak** [comment]
Fixed by commit 203eeda202a14e94940868ae1deadd7125209edf
