### ISSUE TITLE
String is modified on save to AML package

### ISSUE THREAD

**Issue by s-siplivy** [arasplm/ArasVSMethodPlugin#11]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.4.46]
- Innovator 11.0 SP15

### Description
Replace this text with a short description

### Steps to recreate
1. Create C# method with the following code (based on mpp_getWIProcessPlanStructure method from MPP solution):
[test.txt](https://github.com/arasplm/ArasVSMethodPlugin/files/2796818/test.txt)
2. Import with VS plugin
3. Save method anywhere with "Save method to AML package"

### Current behavior
For some reasons string is modified
![image](https://user-images.githubusercontent.com/4171410/51756995-5d7a5f80-20d3-11e9-86c4-38292552fe54.png)

### Expected behavior
String shouldn't be changed

**Comment by mkubrak** [comment]
Fixed by commit 09d9b96e5654ddfb097352d531cd7cf6b3b433a4
