### ISSUE TITLE
New line is added to method after save to AML

### ISSUE THREAD

**Issue by s-siplivy** [arasplm/ArasVSMethodPlugin#12]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.4.46]
- Innovator 11.0 SP15

### Description
New line is added to method after save to AML

### Steps to recreate
1. Create a method with any partial element and save it into AML package
2. Create another project for work with server methods
3. Open the method from AML
4. Save method to AML without changing anything

### Current behavior
New empty line is added to the method
![image](https://user-images.githubusercontent.com/4171410/51757658-04abc680-20d5-11e9-9199-6d2cf7805723.png)

### Expected behavior
Method should remain the same

**Comment by mkubrak** [comment]
Issue fixed in commit 77d232d177ccd822e060834327c46de1b1bdae26. Could you please verify that issue fixed corretly.  You can find build on http://vsixgallery.com/extension/8424E2CB-F5F4-40EA-85B8-260998634ED5/ with number 1.4.62

**Comment by s-siplivy** [comment]
Issue isn't reproduced
