### ISSUE TITLE
[Enhancement] Provide dropbox to select type of new partial element

### ISSUE THREAD

**Issue by s-siplivy** [arasplm/ArasVSMethodPlugin#14]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.4.46]
- Innovator 11.0 SP15

### Description
Provide a dropbox on Create partial element form to select most common element types like e.g. class, interface, enum, struct and custom (similar to current behavior).
It will provide more easier way of files creation.
Notes: default visibility level is internal + attribute is uncommented.

### Steps to recreate
1. Create a new method with plugin
2. RMC on a folder -> select Create Partial Element

**Comment by mkubrak** [comment]
Implemented in 5063e5e7f907e26c016b9659de697cf7c4d59244
