### ISSUE TITLE
[Enhancement] Introduce ability to search methods in AML package dialog

### ISSUE THREAD

**Issue by s-siplivy** [arasplm/ArasVSMethodPlugin#15]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.4.46]
- Innovator 11.0 SP15

### Description
Need an ability to search methods by name in Open method from AML package. It would be nice to be able to search knowing only a part of a method name.

### Steps to recreate
1. Create a method
2. Select Open method from AML package

**Comment by mkubrak** [comment]
Implemented in commit: 03512ca81659bf6dc99f72981e5905c85a52b104
