### ISSUE TITLE
Wrong order for partial class nodes in project config file

### ISSUE THREAD

**Issue by mkubrak** [arasplm/ArasVSMethodPlugin#3]
### Installed product versions
- Visual Studio:  2015 Professional, 2017 Professional
- This extension:  1.2.20

### Description
Partial class nodes should be sorted by ascending in project configuration file.

### Steps to recreate
1. Create method
2. Add partial class with name "ZPartial"
3. Add partial class with name "APartial"

### Current behavior
Partial classes added to project config file as is. First "ZPartial", second "APartial"

### Expected behavior
Partial class nodes should be sorted in alphabetical order

**Comment by s-siplivy** [comment]
Fix may break existing projects, so it isn't required.

**Comment by s-siplivy** [comment]
Fix may mess existing methods, so it isn't required.
Done in commit: ff06302824408b257c591277bd246888c35cadfb
