### ISSUE TITLE
[Enhancement] Need possibility to work with external classes beside of nested ones

### ISSUE THREAD

**Issue by s-siplivy** [arasplm/ArasVSMethodPlugin#42]
### Installed product versions
* Visual Studio: [2015 Professional]
* This extension: [1.4.82]
* Innovator 11.0 SP15

### Description
In PE solution we have a method PE_ChangeItemTransition. When we tried to convert it into plugin compatible method (by adding attributes manually) it appeared that it isn't possible. Because plugin supports only nested classes while method requires external classes support.
Original method code (based on PE 11.0R4):
[PE_ChangeItemTransition.txt](https://github.com/arasplm/ArasVSMethodPlugin/files/2876414/PE_ChangeItemTransition.txt)
Modified method code with attributes (based on PE 11.0R4):
[PE_ChangeItemTransition_v2.txt](https://github.com/arasplm/ArasVSMethodPlugin/files/2876416/PE_ChangeItemTransition_v2.txt)

### Steps to recreate
1. Create a method with code from above.
2. Open method using Visual Studio formatting

### Current behavior
No possibility to convert method (e.g. need extension classes support)

**Comment by s-siplivy** [comment]
Functionality doesn't work (VS15, 1.4.110).
1) Create a new method with Plugin
2) Create a new external interface
3) Try to export to AML/Innovator

![image](https://user-images.githubusercontent.com/4171410/54741305-1db18f00-4bcf-11e9-84cf-466d9be83922.png)

**Comment by s-siplivy** [comment]
1.4.126 [VS15]
It would be very helpful during external elements usage if after the error dialog
![image](https://user-images.githubusercontent.com/4171410/55317529-642da600-5479-11e9-89a3-637d26e63de6.png)
plugin proposes to automatically create fake class inside of MethodCode section (e.g. on the picture below)
![image](https://user-images.githubusercontent.com/4171410/55317455-35afcb00-5479-11e9-90a8-7526f5d7843f.png)

**Comment by s-siplivy** [comment]
On 1.4.139 [VS15] after automatic addition of ArasPluginFin class cntr, del, alt, tab buttons aren't working

**Comment by mkubrak** [comment]
@s-siplivy , Issue fixed,  could you please take the latest version and test this behavior?

**Comment by s-siplivy** [comment]
Another issue was found:
Installed product versions
* Visual Studio: [2017 Professional]
* This extension: [1.5.173]
* Innovator 11.0 SP15

Steps:
1 Create a new method with Plugin
2 Create a new external interface
3 Try to export to AML/Innovator (active tab with main .cs file for the method)
4 Dialog appears (click OK)
![image](https://user-images.githubusercontent.com/4171410/70805636-7282de80-1dca-11ea-97c6-3f7ed6b0c2be.png)
5 The following dialogs appear (click Yes, click OK)
![image](https://user-images.githubusercontent.com/4171410/70805830-f3da7100-1dca-11ea-8f05-9a33084495e7.png)
6 Backspace, delete, etc. buttons stop working in code text editor

**Comment by s-siplivy** [comment]
Validated
