### ISSUE TITLE
"Exception of type 'System.Exception' was thrown" when attempting to save method to Aras Innovator

### ISSUE THREAD

**Issue by MarvinNorway** [arasplm/ArasVSMethodPlugin#65]
### Installed product versions
- Visual Studio: 2017 Professional, 15.9.12
- This extension: ArasVSMethodPlugin 1.4.139

### Description
After merging two Git branches, it is no longer possible to "Save method to Aras Innovator."
I have since switched back to the previous version of my code (where this feature still worked), but the problem did not go away - so it might just have been a coincidence. I have even reinstalled the plugin and restarted my machine, but this did not help either. Nor did downgrading to 1.4.126.

### Current behavior
When choosing "Save method to Aras Innovator" from the menu ribbon, Aras VS method plugin displays an error message that says nothing except "Exception of type 'System.Exception' was thrown."
This happens with *all* methods in the project. I don't have other projects to test this with.

### Expected behavior
The method should be saved to Aras Innovator.

Is there a log somewhere or some other way to get more information about the exception? The error message really should be improved.

![image](https://user-images.githubusercontent.com/2988908/59026740-718b5600-8857-11e9-9412-a4a858655981.png)

**Comment by MarvinNorway** [comment]
Update:
Saving methods to an AML package did not work either.
However, I was able to solve the issue by updating the method from Aras Innovator.
This, however, does not solve the problem of the poor error message.

**Comment by VladymyrAfanasiev** [comment]
Fixed.

Revision: 1eb1c8f9ffa6b9cbb823787c7d810447328b4926
Author: Volodymyr Afanasiev <s-vafanasiev@aras.com>
Date: 6/14/2019 2:21:07 PM
Message:
"Exception of type 'System.Exception' was thrown" when attempting to save method to Aras Innovator

null check of string has been replace
by 'string.IsNullOrEmpty'
----
Modified: Aras.VS.MethodPlugin/Commands/SaveToArasCmd.cs

**Comment by mkubrak** [comment]
@MarvinNorway , could you please download latest build and check if the issue resolved on your environment? Here link where you can find new build http://vsixgallery.com/extension/8424E2CB-F5F4-40EA-85B8-260998634ED5/. Thanks.

**Comment by MarvinNorway** [comment]
I'm not sure if I can reproduce this now as I have changed the code now and I'm not sure if I can reproduce the corrupted files.
But I'll keep an eye on this, thank you!

By the way, is the new version compatible with Visual Studio 2019?

**Comment by mkubrak** [comment]
@MarvinNorway, no current version is not compatible with 2019. Compatibility will be uploaded in a week.

**Comment by MarvinNorway** [comment]
Thanks, that sounds great! Could you please put that into the release notes then?
I haven't installed VS2019 yet, but as soon as the plugin supports it, I'd like to make the switch.
Thank you!
