### ISSUE TITLE
Downloaded Server Method Directory

### ISSUE THREAD

**Issue by VirtualWebSoftware** [arasplm/ArasVSMethodPlugin#71]
### Installed product versions
- Visual Studio: 2017, 2019
- This extension: [example 1.1.21] - Aras Innovator Method Plugin v1.4.151 

### Description
When opening methods from Aras, the directory created in VS contains unexpected sub directories - each word shown here results in a directory of the same name, with the downloaded method contained in the last directory created.

ServerMethods - com - aras  - innovator - solution - PLM - Import - Method - <Method Name>

the expected would be:

ServerMethods - <Method Name> - 

### Steps to recreate
1. connect to Aras server, Open any C# method from innovator

### Current behavior
Too many directories created

![image](https://user-images.githubusercontent.com/20202231/65890001-31a12f00-e370-11e9-8e96-e35d7bf81f77.png)

**Comment by VladymyrAfanasiev** [comment]
Hello,

We have implemented a new approach to generate a method folder tree. We used approach from export utility.

Export utility generate path for each exported item, we generate the same path for our methods.

Additional info:
'core' packages have few specific cases:
-  "com.aras.innovator.solution.***.***..." packages -  path of the package is the end of expression.
- "com.aras.defaults.***.***..." or "com.aras.innovator.***.***..." packages, but not first case  - points in name replace by '/' and in result, we take a package path.

**Comment by VirtualWebSoftware** [comment]
I don't fully understand the way packages are used within Aras.  But, I see how separating methods into a more functional grouping is nice in order to quickly identify customizations vs base  methods.   However, the depth of the tree structure is a bit overwhelming, and opening old projects created with previous versions would be nice.
