### ISSUE TITLE
Useless error messages upon opening project dialogs

### ISSUE THREAD

**Issue by MarvinNorway** [arasplm/ArasVSMethodPlugin#72]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.4.148

### Description
Connection Info dialog shows an error about a NullReferenceException.

### Steps to recreate
1. Right click on project title in Solution Explorer
2. Aras Innovator -> Any option there

### Current behavior
Error message:

- Update project configuration, Connection info: "Object reference not set to an instance of an object" (obviously NullReferenceException)
- All other options: "Value cannot be null. Parameter name: path2" (obviously ArgumentNullException)

### Expected behavior
It should at least show a better error message.
Probably something is wrong with my project configuration, but this isn't a great user experience.

**Comment by VirtualWebSoftware** [comment]
I can confirm this behavior.  Seems to happen on all projects created with a previous version of the extension

**Comment by VladymyrAfanasiev** [comment]
@MarvinNorway , we added fix for this and now the VS Method plugin shows more information on any error.

**Comment by VladymyrAfanasiev** [comment]
Revision: 4d87421adf1051f3ab96aef7736af6f03c42e22d
Author: Volodymyr Afanasiev <s-vafanasiev@aras.com>
Date: 10/1/2019 4:51:39 PM
Message:
72 Useless error messages upon opening project dialogs. Added messages where a project config file is broken.

Added error messages on Load/Save of project config.
Added show of full exception (earlier only message).
----
Modified: Aras.Method.Libs/Configurations/ProjectConfigurations/ProjectConfigurationManager.cs
Modified: Aras.Method.Libs/MessageManager.cs
Modified: Aras.VS.MethodPlugin.Tests/Commands/ConnectionInfoCmdTest.cs
Modified: Aras.VS.MethodPlugin.Tests/Commands/CreateMethodCmdTest.cs
Modified: Aras.VS.MethodPlugin.Tests/Commands/DebugMethodCmdTest.cs
Modified: Aras.VS.MethodPlugin.Tests/Commands/RefreshConfigCmdTest.cs
Modified: Aras.VS.MethodPlugin.Tests/ProjectConfiguration/ProjectConfigurationManagerTest.cs
Modified: Aras.VS.MethodPlugin/ArasMainMenuCmdPackage.cs
Modified: Aras.VS.MethodPlugin/Commands/CmdBase.cs
