### ISSUE TITLE
Plugin requires methods to reside in "Import\Methods" folder

### ISSUE THREAD

**Issue by MarvinNorway** [arasplm/ArasVSMethodPlugin#74]
### Installed product versions
- Visual Studio: 2019 Professional (16.2.3)
- This extension: 1.4.148

### Description
The Visual Studio template creates a structure with a "ServerMethods" folder. For years, we have placed our methods into this folder, like this:

ServerMethods
+---Method1
        +-----Method1.cs
        +-----Method1Tests.cs
        +-----Method1Wrapper.cs

The methods are part of a package, like "com.company.product", but this has never had any influence on the path.
I have noticed that when I open methods from Innovator, they are now stored in "ServerMethods\com\company\product\Import\Method\<MethodName>\<MethodName>.cs", while existing methods like "ServerMethod\Method1\Method1.cs" cannot be saved to Innovator anymore, the option is gone.

However, when I move my folder "Method1" from "ServerMethod" to "ServerMethod\Import\Method\Method1" (new folder), then the option "Save to Innovator" becomes available again.

When was this breaking change introduced? This is not great.
Do we have to move the files in our solution?

**Comment by MarvinNorway** [comment]
Fantastic. I have now moved my method to ServerMethods\Import\Method\Method1, so the "Save to Innovator" option becomes available.
And when I try to save it, this is the result:

![image](https://user-images.githubusercontent.com/2988908/65982884-9b0e6400-e47c-11e9-9187-b4b62dab3b22.png)

Really frustrating. Another good reason to move away from Aras Innovator as quickly as possible and never look back. I don't want to think about how much money this terrible piece of software has cost my client already.

**Comment by VirtualWebSoftware** [comment]
My experience seems to indicate the new extension is not compatible with projects created with a previous version.   When I installed the old version, the errors disappeared.

**Comment by MarvinNorway** [comment]
Which "old version" did you use? The old version I used was not compatible with VS 2019. That's why I uninstalled it, together with VS2017, when I installed VS 2019. Until now, I didn't have a need to install the plugin again.
Seems like nobody bothers to test the extension before releasing new versions.

**Comment by MarvinNorway** [comment]
Is there an old version available for download somewhere?
Really frustrating that no one (@mkubrak ?) updates this issue...

**Comment by mkubrak** [comment]
@MarvinNorway , sorry for this issue. VS Method plugin change project structure which common for Customer Repository Template but we did not add support for the previous structure. We will create a new build to fix issues #71. We are working on functionality to upgrade structure of projects to new approach. Please expect it in the near future.

**Comment by mkubrak** [comment]
@MarvinNorway  you can download the previous version from https://ci.appveyor.com/project/mkubrak/arasvsmethodplugin/builds/25193859/artifacts.

**Comment by MarvinNorway** [comment]
Thank you!

**Comment by VladymyrAfanasiev** [comment]
@MarvinNorway we added new node _UseCommonProjectStructure_ to any project config file that indicates project structure:
- _False_ means previous structure
- _True_ means common structure (for Customer Repository Template)

If this node does not exist in project config file, VS Method plugin will set _False_ and as result the plugin will work with templates created earlye.

This feature was checked, please try next build and confirm the issue is fixed : https://ci.appveyor.com/project/mkubrak/arasvsmethodplugin/builds/28153655/artifacts
