### ISSUE TITLE
Package not detected

### ISSUE THREAD

**Issue by bidolah** [arasplm/ArasVSMethodPlugin#82]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.5.167

### Steps to recreate
1. Click "Open method from aras innovator"
2. Select method from innovator instance 
3. "Packaged Name" of the method not detected but method already in the package 

Possible additional steps:
1) Create server method with some name, for example test1
2) Add method to the new package 
3) Rename method and save, for example test2
4) Try to open the method with plugin
.

**Comment by bidolah** [comment]
@VladymyrAfanasiev

**Comment by VladymyrAfanasiev** [comment]
Fixed.

Revision: a6e123f98c14766aa4fb7d29fcbf9f98b0b1ac85
Author: Volodymyr Afanasiev
Date: 11/13/2019 12:06:50 PM
Message:
82 Package not detected. Criteria to find a package has been changed to item 'config_id' (earlier name')'

'config_id' property is unique for
eatch item.
----
Modified: Aras.VS.MethodPlugin.Tests/PackageManagement/PackageManagementTest.cs
Modified: Aras.VS.MethodPlugin/Commands/SaveToArasCmd.cs
Modified: Aras.VS.MethodPlugin/Dialogs/ViewModels/OpenFromArasViewModel.cs
Modified: Aras.VS.MethodPlugin/Dialogs/ViewModels/SaveMethodViewModel.cs
Modified: Aras.VS.MethodPlugin/Dialogs/ViewModels/UpdateFromArasViewModel.cs
Modified: Aras.VS.MethodPlugin/PackageManagement/PackageManager.cs

**Comment by VladymyrAfanasiev** [comment]
@bidolah Please review the fix.

**Comment by bidolah** [comment]
I hope the fix works, close it without review.
