### ISSUE TITLE
Endregion tag is on incorrect line

### ISSUE THREAD

**Issue by s-siplivy** [arasplm/ArasVSMethodPlugin#9]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.4.46]

### Description
Replace this text with a short description

### Steps to recreate
1. Create a new C# method Test with any code. For example just "return null;"
2. Open method in Visual Studio

### Current behavior
endregion tag is on the last line of the code
![image](https://user-images.githubusercontent.com/4171410/51755682-59007780-20d0-11e9-9d1b-bde33a0c8c36.png)

### Expected behavior
endregion should be on the next line after the code, otherwise there is compilation error

**Comment by mkubrak** [comment]
Fixed in commit 2b322bf3d1c68d8be3fd1119497f3b74259577a7
