### ISSUE TITLE
Missing semicolon for //MethodTemplateName={0};

### ISSUE THREAD

**Issue by gunnarsuhr** [arasplm/ArasVSMethodPlugin#96]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Enterprise 2019
- This extension: 1.5
- Innovator 11SP15

### Description
When using the comment MethodTemplateName, the semicolon at the end of the comment is missing.
This throws error

### Steps to recreate
1. Create a server-side method in Aras Innovator and named it somehow
2. Edit method in Aras Innovator and add for example "//MethodTemplateName=CSharpInOut;"
3. Save method and to a package definition
4. Do 'Check Syntax' ![image](https://user-images.githubusercontent.com/23652027/88266761-06f1df80-ccd0-11ea-9bed-e2c84ec5e843.png) -> Result should be ok
5. Unlock method
6. Load method to Visual Studio using plugin
7. modify something and save changes to Innovator
8. Open method in innovator and 'Check Syntax' -> Result error, because default template has been used, because of missing semicolon at comment for MethodTemplateName

### Current behavior
see step 8

### Expected behavior
Semicolon should be added ... Seems that 'SaveToArasCmd.cs' forgets the semicolon, when inserting the comments

**Comment by EliJDonahue** [comment]
Thanks, gunnarsuhr. This issue has been passed on to the team and will be reviewed.

**Comment by sergeyshapka** [comment]
This issue was fixed in commit [f799544] inside #97 pull request
